### PR TITLE
Add support for Github Actions

### PR DESCRIPTION
**Pull request by pkarakal**
This adds a CI pipeline that builds the image in github actions and publishes it to docker hub registry. 

This will automate the image publication and the maintainers will not have to manually upload the image

The pipeline will only run on the master branch. If creating an image on pull requests is something you want, I can also work on that.

### CODE REVIEW

**Comment by bnase** [comment]
> yes. they serve the same purpose (CI/CD)

I have already connected everything to https://hub.docker.com/repository/docker/authcsal/docker. So what does this add? I am afraid it's just another file to maintain :(

**Comment by pkarakal** [comment]
> > yes. they serve the same purpose (CI/CD)
> 
> I have already connected everything to https://hub.docker.com/repository/docker/authcsal/docker. So what does this add? I am afraid it's just another file to maintain :(

This builds the docker image on Github Actions and pushes it to docker hub (so that you don't have to do it on your machine).  When you say you have them connected, do you mean that the image is getting built on docker hub? if that's the case, I think I can close this PR

**Comment by bnase** [comment]
> > > yes. they serve the same purpose (CI/CD)
> > 
> > 
> > I have already connected everything to https://hub.docker.com/repository/docker/authcsal/docker. So what does this add? I am afraid it's just another file to maintain :(
> 
> This builds the docker image on Github Actions and pushes it to docker hub (so that you don't have to do it on your machine). When you say you have them connected, do you mean that the image is getting built on docker hub? if that's the case, I think I can close this PR

yes, already doing automated builds 
image

**Comment by pkarakal** [comment]
> yes, already doing automated builds 
> image

Perfect. Feel free to close this :v:

**Pull request closed without merging**
